<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.8.10 on linux)" generated="20220128 18:41:35.705" rpa="false" schemaversion="2">
<suite id="s1" name="Test" source="/home/qa/PycharmProjects/pythonProject/Test.robot">
<test id="s1-t1" name="Open Browser">
<status status="FAIL" starttime="20220128 18:41:35.740" endtime="20220128 18:41:35.741">Test case contains no keywords.</status>
</test>
<test id="s1-t2" name="open the browser">
<status status="FAIL" starttime="20220128 18:41:35.741" endtime="20220128 18:41:35.745">Test case contains no keywords.</status>
</test>
<test id="s1-t3" name="Search on Google">
<status status="FAIL" starttime="20220128 18:41:35.746" endtime="20220128 18:41:35.746">Test case contains no keywords.</status>
</test>
<test id="s1-t4" name="search topic browserstack">
<status status="FAIL" starttime="20220128 18:41:35.746" endtime="20220128 18:41:35.747">Test case contains no keywords.</status>
</test>
<status status="FAIL" starttime="20220128 18:41:35.706" endtime="20220128 18:41:35.747"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="4" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="4" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220128 18:41:35.734" level="ERROR">Error in file '/home/qa/PycharmProjects/pythonProject/Test.robot' on line 3: Importing library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/lib/python38.zip
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
